### ISSUE TITLE
macOS / MPS support

### ISSUE THREAD

**Issue by ChristianWeyer** [Finity-Alpha/appointment-demo#1]
Is there any way to have performance-optimized mac/MPS support?
Thanks!

**Comment by fakhirali** [comment]
The demo is made on top of OpenVoiceChat, using it's premade model classes. You can add any custom stt, tts or llm model implementation to it **extremely easily,** see how to do it [here](https://www.finityalpha.com/OpenVoiceChat/Adding_models/). So any mps model specific stuff would go there. 
I believe you can [run](https://github.com/openai/whisper/discussions/984#discussioncomment-5078938) the huggingface whisper (and other models) using 
```python 
device = torch.device("mps")
```

Do let me know if you need any further help. I do have an iMac at home to test things out!

**Comment by ChristianWeyer** [comment]
Adding this to the sample here was easy enough ;-)

```
    if torch.backends.mps.is_available():
        device = 'mps'
    elif torch.cuda.is_available():
        device = 'cuda'
    else:
        device = 'cpu'
```
